### ISSUE TITLE
TypeError: Cannot read property 'txid' of undefined

### ISSUE THREAD

**Issue by scriptzteam** [bitpay/insight-ui#700]
when in its still in sync sometimes it stopping itself, i had to start it again ...

[2015-12-18T13:29:17.282Z] error: uncaught exception: [TypeError: Cannot read property 'txid' of undefined]
[2015-12-18T13:29:17.284Z] error: TypeError: Cannot read property 'txid' of undefined
    at /root/mynode/node_modules/bitcore-node/lib/services/address/index.js:1474:46
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:721:13
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:52:16
    at done (/root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:246:17)
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:44:16
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:718:17
    at /root/mynode/node_modules/bitcore-node/node_modules/async/lib/async.js:167:37
    at /root/mynode/node_modules/bitcore-node/lib/services/address/index.js:1423:11
    at /root/mynode/node_modules/bitcore-node/lib/services/address/index.js:1180:9
    at ReadStream.<anonymous> (/root/mynode/node_modules/bitcore-node/lib/services/address/index.js:1239:5)
[2015-12-18T13:29:17.284Z] info: Beginning shutdown
[2015-12-18T13:29:17.285Z] info: Stopping insight-ui
[2015-12-18T13:29:17.285Z] info: Stopping insight-api
[2015-12-18T13:29:17.285Z] info: Stopping web
[2015-12-18T13:29:17.286Z] info: Stopping address
[2015-12-18T13:29:17.286Z] info: Stopping db
[2015-12-18T13:29:17.307Z] info: Stopping bitcoind
[2015-12-18T13:29:18.307Z] info: bitcoind shutdown.

**Comment by braydonf** [comment]
Outdated
