### ISSUE TITLE
RPCError: Verifying blocks

### ISSUE THREAD

**Issue by diadal** [bitpay/insight-ui#740]
2016-10-02T09:35:01.772Z] error: Failed to start services
[2016-10-02T09:35:01.773Z] error: RPCError: Verifying blocks...
    at Bitcoin._wrapRPCError (/Users/administrator/.bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:449:13)
    at /Users/administrator/.bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:780:28
    at IncomingMessage.<anonymous> (/Users/administrator/.bitcore/node_modules/bitcoind-rpc/lib/index.js:107:7)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[2016-10-02T09:35:01.773Z] info: Beginning shutdown
[2016-10-02T09:35:01.773Z] info: Stopping insight-ui (not started)
[2016-10-02T09:35:01.774Z] info: Stopping insight-api (not started)
[2016-10-02T09:35:01.774Z] info: Stopping web (not started)
[2016-10-02T09:35:01.775Z] info: Stopping bitcoind
[2016-10-02T09:35:12.128Z] error: Failed to stop services: Error: bitcoind spawned process exited with status code: 1

**Comment by gabegattis** [comment]
@diadal What OS and node version are you using?

**Comment by diadal** [comment]
mac os node version 4

**Comment by Levino** [comment]
Same error here. Any solution to this?

**Comment by diadal** [comment]
you need to use bitcoind 12 version if you have 13 version then you get that error

**Comment by Levino** [comment]
I use the one shipped with insight / bitcore.

**Comment by diadal** [comment]
that will be v12 you may need to bitcoin core 12 and use the same data folder allow bitcoin core to build the and verified block once this is done your bitcore nodes should able to start

**Comment by DAVIFONT** [comment]
Minha transação não aparece, como se não tivesse sido feita e não sai da informação (processando), o que fazer????? o código hash https://insight.bitpay.com/tx/cf858737c23681cc507e4b05ebb4cddb1ec0050433a4dbbcb9f1cc6d5ce9da3a

Eles ficam com o dinheiro e nos no prejuizo?? que palhacada é essa?
